name: Go vulnerabilities check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check for go vulnerabilities
      uses: opzkit/govulncheck-action@v1.0.0
      # optional
      with:
        go-version: '1.19'
        govuln-version: 'latest'
        packages: './...'
